server:
  port: 9001
  servlet:
    context-path: /api

jwt:
  header: Authorization
  secret: N6GQ/kmiiKHA3SYEk2CooLkykzxbp7Ha7eJebaeIK2k=
  expiration: 1000

logging:
  level:
    org.springframework.security: DEBUG

host:
  url: localhost:9001/ms
  path:
    message: /hello/getMessage

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
